### ISSUE TITLE
A way to link the map by the Geohash?

### ISSUE THREAD

**Issue by ppKrauss** [missinglink/leaflet-spatial-prefix-tree#4]
Hi, there are a way to use something like <br/>`http://mapzen.github.io/leaflet-spatial-prefix-tree/{myGeohash}` <br/>?

**Comment by missinglink** [comment]
There is not currently support for sharing links to geohashes.

I know http://geohash.org offers this functionality.

As it's hosted on GitHub pages any parameter would have to be part of the url anchor.

We'd be happy to accept a PR for this.

**Comment by ppKrauss** [comment]
Oops sorry, it is Javascript. Ok, suppose a [cool URI](https://www.w3.org/TR/cooluris/) using `#`, that is, 
`http://mapzen.github.io/leaflet-spatial-prefix-tree#{myGeohash}`. 

Implementation: use`window.location.hash`. See [`location` properties](https://developer.mozilla.org/en-US/docs/Web/API/Window/location#Example_6_Using_bookmarks_without_changing_the_hash_property) or [onhashchange](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange).

PS: the formal name of the "hash" in the [URI scheme](https://en.wikipedia.org/wiki/URL#Syntax)  is *fragment*.
